GET http://127.0.0.1:8000/api/courses/1/

###
GET http://127.0.0.1:8000/assessments/

### GET a Single Assessment
DELETE http://127.0.0.1:8000/api/courses/1/comments/2/


### POST a COMMENT Assessment
POST http://127.0.0.1:8000/api/courses/1/comments/
Content-Type: application/json

{
  "content":"AMAZING SHIZZ!"
}