# Generated by Django 3.2.4 on 2021-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20210616_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LRN', 'Learner'), ('INS', 'Instructor')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
