# Generated by Django 3.2.4 on 2021-06-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_user_rating'),
        ('jwt_auth', '0006_auto_20210616_1445'),
    ]

    operations = [
    ]
