# Generated by Django 3.2.4 on 2021-06-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_merge_0005_alter_user_rating_0006_auto_20210616_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
