# Generated by Django 3.2.4 on 2021-06-17 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
