# Generated by Django 3.2.4 on 2021-06-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_rename_rated_by_course_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rating',
            new_name='rating_by',
        ),
    ]
